# Generated by Django 5.1.4 on 2024-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0002_alter_userdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
